### PR TITLE
Add the --od option (main output file directory)

### PR DESCRIPTION
**Pull request by marler8997**
I also added a test to make sure that option `--od` uses the "buildWitness".  I need to make sure we also test that the buildWitness is used with all combinations of `-o*` switches.

### CODE REVIEW

**Comment by CyberShadow** [comment]
Doesn't seem to work:

```console
$ rund --od. prog  
Error: unrecognized switch '--od.'
       run 'dmd -man' to open browser on manual
```

Also, something seems to have gone wrong with `-od`:

```console
$ echo 'void main() {}' > prog.d

$ rund -od. prog

$ rund -od. prog
Usage: rund [rund/compiler options]... program.d [program options]...

[...]
```

On the second invocation it is confused by the presence of `prog` in the same directory.

Could we maybe go back to getting `rdmd` to understand `dmd -I`? Was there anything missing in your pull request? Maybe I can finish it?

**Comment by marler8997** [comment]
`--od.` doesn't work because I haven't decided that `rund` should support different ways of giving option arguments yet.  Supporting the omission of `=` also paints you into a corner if you ever want another switch starting with the same thing, `--odd`...is that `--od=d` or a new option `--odd`?  Because of the last problem...if we were to add another way to support option arguments, I'd be more inclined to support `--od <dir>`, especially since some shells don't support tab-completion with `--od=<dir>`.

> On the second invocation it is confused by the presence of prog in the same directory.

For this issue, we should take a look at the algorithm `rund` uses to find the main source file and see if it can be improved.  The use case you've brought up is quite unexpected for the user.  I'll summarize the algorithm and we can decide how to move forward:

1. for each command line argument starting from the leftmost
2. does it start with `-`? If so, then check if it's a rund option, if it's not recognized forward to the compiler.
3. else (doesn't start with `-`), must be a file, get its attributes
4. if it doesn't exist and doesn't end in ".d", try appending ".d"
5. if it is a symbolic link, resolve it
6. if the final file ends in ".d", then it's our main source file...stop processing arguments, otherwise, it must be a file that should be passed to the compiler

So after you compiled `prog.d` the first time it saw that `prog` was already a file so it didn't append `.d`.  Since it was a file and didn't end in `.d`, rund assumes this must be a file meant for the compiler, it could be a library or some other type of input file the compiler supports.

Some things to consider.  As the algorithm stands today, `rund` doesn't need to know the underlying compiler's command line interface, except for the options it uses.  This means `rund` will still work with new compilers even if they add/change their arguments so long as they don't remove support for the ones `rund` relies on.

> Could we maybe go back to getting rdmd to understand dmd -I? Was there anything missing in your pull request? Maybe I can finish it?

PR is here https://github.com/dlang/tools/pull/292. I recall that I had gotten it working somewhat using output from `-v`, but realized that had problems cause now error messages wouldn't get back to the user.  So I was waiting for the new json output (which `rund` now uses).  If you want to finish it you are welcome...feel free to take anything from `rund` if you like as well. But be warned that its not going to be easy...I put a lot of work into it and I felt like we needed to really beef up the testing before releasing it.

**Comment by marler8997** [comment]
Actually, now that I'm looking at the PR...it looks like I may have already added JSON support :)

**Comment by marler8997** [comment]
Also...`rdmd` has alot of bugs already that were fixed with `rund`....I don't remember them all but as I refactored the code I remember seeing quite a few of them.

**Comment by CyberShadow** [comment]
> `--od.` doesn't work because I haven't decided that `rund` should support different ways of giving option arguments yet.

Ah, OK. Maybe being more explicit about it would help.

The only double-dash switches DMD has are `--help` and `--version`, so it's safe to assume that any switch starting with `--` is meant for `rund`, and if `rund` doesn't recognize it, it might as well complain about it.

> The use case you've brought up is quite unexpected for the user.

Sorry, do you mean that the use case is unusual? Because I disagree, I don't see anything unusual about that session, and rund's behavior is surprising.

> So after you compiled `prog.d` the first time it saw that `prog` was already a file so it didn't append `.d`. Since it was a file and didn't end in `.d`, rund assumes this must be a file meant for the compiler, it could be a library or some other type of input file the compiler supports.

In any case, `dmd` does the same thing with file names without an extension: it appends `.d`. So, it can be safe to assume that passing a *file* without an extension to `dmd` is nonsensical.

> PR is here [dlang/tools#292](https://github.com/dlang/tools/pull/292). I recall that I had gotten it working somewhat using output from `-v`, but realized that had problems cause now error messages wouldn't get back to the user. So I was waiting for the new json output (which `rund` now uses). If you want to finish it you are welcome...feel free to take anything from `rund` if you like as well. But be warned that its not going to be easy...I put a lot of work into it and I felt like we needed to really beef up the testing before releasing it.

Thanks!

**Comment by marler8997** [comment]
> Sorry, do you mean that the use case is unusual? Because I disagree, I don't see anything unusual about that session, and rund's behavior is surprising.

No I meant unexpected behavior...it's a good use case to address.

**Comment by marler8997** [comment]
> In any case, dmd does the same thing with file names without an extension: it appends .d. So, it can be safe to assume that passing a file without an extension to dmd is nonsensical.

OH!  Well that makes it easy then!

**Comment by CyberShadow** [comment]
Thanks! I'll give it a go.

**Comment by marler8997** [comment]
FYI...I realized that fix broke symbolic links:
```bash
$ echo 'void main() {}' > prog.d
$ ln -s prog.d prog_link
$ rund prog_link
rund: Error: prog_link.d doesn't exist
```
But luckily with the new assumption that files with no extensions must be D source files...I was still able to modify the algorithm to work correctly...I've update the PR if you want to test anything else.

**Pull request merged**
